//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Rules_BOND_CPP.tt
//     File     : bond_enum.h
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    

#pragma once

#include "bond_const_enum.h"

namespace bond
{
namespace _bond_enumerators
{
namespace Modifier
{


enum Modifier
{
    Optional,
    Required,
    RequiredOptional,
}; // enum Modifier

}  // namespace Modifier
}  // namespace _bond_enumerators

using namespace _bond_enumerators::Modifier;


} // namespace bond
